export { default as ButtonComp } from "./Button"
export { default as HeaderComp } from "./Header"
export { default as CardSocialComp } from "./CardSocial"
export { default as CardComp } from "./Card"
export { default as LoadingComp } from "./Loading"